print ("Welcome to the Basic Recon Tool!")
target_domain= input ("Enter target domain/name:\n")
target_IP_add= input ("Enter target IP address:\n")
port_number = int(input("Enter the port number to scan:\n"))
print ("[+] Analyzing Data...")
print ("Target Domain Length: " +str (len(target_domain))  + " characters.")
print ("Target IP Length:" + str(  len(target_IP_add)) + ("characters."))
print ("Port Data Type Confirmed:" +str(type(port_number)) )
print ("")
print ("[+] Final Scan Report:")
print ("You are targeting " + target_domain + " with " + target_IP_add + " on " + str (port_number) + ". Good luck!")